import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { text } from 'stream/consumers'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className="resume">
          <div className="resume_left">
            <div className="resume_profile">


            </div>
            <div className="resume_content">
              <div className="resume_item resume_info">
                <div className="title">
                  <p className="bold_nom">Sarah OUALI</p>
                  <p className="regular">Etudiante en 1ére année informatique chez Enigma</p>
                </div>
                <ul>
                  <li>
                    <div className="icon">
                      <i className="fas fa-map-signs"></i>
                    </div>
                    <div className="data">
                      <a
                        href="https://www.google.com/maps/place/1+Rue+Laurent+Lavoisier,+59370+Mons-en-Bar%C5%93ul/@50.6349435,3.1041019,17z/data=!3m1!4b1!4m6!3m5!1s0x47c2d603c82d3f39:0x86fadb506d3ea4bd!8m2!3d50.6349401!4d3.1066768!16s%2Fg%2F11c1c2mvlm"
                      >1 rue Laurent Lavoisier<br />
                        Mons-en-Baroeul 59370 <br />
                        France</a
                      >
                    </div>
                  </li>
                  <li>
                    <div className="icon">
                      <i className="fas fa-mobile-alt"></i>
                    </div>
                    <div className="data">07 52 02 93 56 </div>
                  </li>
                  <li>
                    <div className="icon">
                      <i className="fas fa-envelope"></i>
                    </div>
                    <div className="data">
                      <a href="mailto:oualis888@gmail.com"
                      >oualis888<br />@gmail.com</a
                      >
                    </div>
                  </li>
                  <li>
                    <div className="icon">
                      <i className="fab fa-github"></i>
                    </div>
                    <div className="data">
                      <a href="https://github.com/sarahouali">github.com/sarahouali</a>
                    </div>
                  </li>
                </ul>
              </div>
              <div className="resume_item resume_skills">
                <div className="title">
                  <p className="bold">Compétences</p>
                </div>
                <ul>
                  <li>
                    <div className="skill_name">•SQL</div>
                  </li>
                  <li>
                    <div className="skill_name">•Reseau informatique (Cisco CCNA 1)</div>
                  </li>
                  <li>
                    <div className="skill_name">•Administration LINUX</div>
                  </li>
                  <li>
                    <div className="skill_name">• Gestion de projet</div>
                  </li>
                  <li>
                    <div className="skill_name">•Html/Css</div>

                  </li>
                  <li>
                    <div className="skill_name">•java</div>
                  </li>

                </ul>
              </div>
              <div className="resume_item resume_social">
                <div className="title">
                  <p className="bold">Reseaux Sociaux</p>
                </div>
                <ul>
                  <li>
                    <div className="icon">
                      <i className="fab fa-twitter-square"></i>
                    </div>
                    <div className="data">
                      <p className="semi-bold">Instagram</p>
                      <p>
                        <a href="https://www.instagram.com/sarxxh.oli/"
                        >instagram.com/sarxxh.oli/</a
                        >
                      </p>
                    </div>
                  </li>

                  <li>
                    <div className="icon">
                      <i className="fab fa-linkedin"></i>
                    </div>
                    <div className="data">
                      <p className="semi-bold">Linkedin</p>
                      <p>
                        <a
                          href="https://www.linkedin.com/in/sarah-ouali-375008240/"
                        >Sarah-ouali@linkedin/</a
                        >
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
              <div className="title">
                <p className="bold">Diplomes & Certificats</p>
              </div>
              <div className="interet">
                <ul className="centres-interet">
                  <li>
                    <div className="skill_name">• Baccalauréat S </div>
                  </li>
                  <li>
                    <div className="skill_name">• Certificate of English C1</div>
                  </li>
                  <li>
                    <div className="skill_name">• Certification Cisco CCNA 1</div>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          <div className="resume_right">
            <div className="resume_item resume_about">
              <div className="title">
                <p className="bold">Profil Personnel</p>
              </div>
              <p>
                je suis étudiante en première année de bachelor à l'école supérieure d'informatique ENIGMA ,
                Le volley est ma passion ( je suis volleyeuse depuis 2009).
                Je suis passionnée de Sécurité informatique, réseaux et data.
              </p>
            </div>
            <div className="resume_item resume_work">
              <div className="title">
                <p className="bold">Expériences professionnelles
                </p>
              </div>
              <ul>
                <li>
                  <div className="date">Projet Universitaire</div>
                  <div className="info">
                    <p className="semi-bold">Boutique en ligne (2021)</p>

                    <p>
                      • Création d'un site web e-commerce d'une
                      boutique en ligne (Via HTML)
                    </p>
                    <p>
                      • Mise en forme de l'aspect visuel de la
                      boutique via CSS
                    </p>
                    <p>
                      • Dynamisation du site via JavaScript

                    </p>
                  </div>
                </li>
                <li>
                  <div className="date"> Job d'été Secrétaire Notariale (Juin- Juillet 2022)</div>
                  <div className="info">
                    <p className="semi-bold">

                      • Utilisation du pack Office pour les tâches quotidiennes et la production des documents demandés.
                    </p>
                    <p>• Rédaction d'actes (Procurations, Vente,..)
                    </p>
                    <p>• Planification de rendez-vous avec clients</p>
                  </div>
                </li>
                <li>
                  <div className="date">INEO Equans Hauts de France  (juin-Septembre 2023)</div>
                  <div className="info">
                    <p className="semi-bold">Stage Développeur Mainteneur Outils Informatiques</p>
                    <p className="logotravail"></p>
                    <p>
                      • Technologies ( Pack Office 365, Power automate, Power BI, Power apps , SharePoint, KizeoForm, API Rest)

                    </p>
                    <p> • Langages ( Low code, PowerFx, DAX, M, Json)
                    </p>
                    <p> •	Création de rapports sous Power BI (langage DAX et SQL),</p>
                    <p>• Développement des outils, des plateformes sous Power BI, test et mise en route)</p>
                    <p> •	Création de système automatisé sous Power Automate.

                    </p>
                    <p> •	Développement sous Excel VBA</p>
                    <p>
                      •	Création de formulaire dynamique sous KIZEO (API REST, Json)
                    </p>


                  </div>
                </li>
              </ul>
            </div>
            <div className="resume_item resume_education">
              <div className="title">
                <p className="bold">Formations</p>
              </div>
              <ul>
                <li>
                  <div className="date">En cours</div>
                  <div className="info">
                    <p className="semi-bold">Enigma Ecole Supérieure d'informatique (Lille,59)</p>
                    <p> (Bac+1) Bachelor Responsable de Projets Informatiques</p>
                    <p>• Très passionnée de sécurité informatique, big data, réseaux et numérique.</p>
                  </div>
                </li>
                <li>
                  <div className="date">2021-2023</div>
                  <div className="info">
                    <p className="semi-bold">Licence 2 Informatique</p>
                    <p>Université Abderrahmane Mira Béjaia</p>
                    <p>• Membre du club Scientifique Informatique de la faculté sciences exactes (CSI)</p>
                    <p> • Fort interét aux statisiques, Algébre linéaire, Analyse mathématique et bases de données</p>
                  </div>
                </li>
                <li>
                  <div className="date">Lycée Chouhada Annani (Béjaia, Algérie)</div>
                  <div className="info">
                    <p className="semi-bold">Diplômée en 2020 - Mention Bien</p>
                    <p>• Membre du club scientifique informatique

                    </p>
                    <p> • Membre de l'équipe de volleyball du lycée</p>
                  </div>
                </li>

                <li>
                  <div className="date" > Centre d'interet</div>
                  <div className="info">
                    <p>Volleyball</p>
                    <p>Voyages </p>
                    <p> Cuisine</p>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>

      </main>
    </main>
  )

}
